#!/bin/bash
# =============================================================================
# Import C&S 2026 Charge Maps into Salesforce
#
# This script imports data in 3 sequential steps:
# 1. Create Opportunities (one per Account, Renewal record type)
# 2. Create Charge Maps (one per Account, linked to Opportunity)
# 3. Create Charge Map Items (one per line, linked to Charge Map)
#
# Prerequisites:
#   - sf CLI authenticated to PixidProd org
#   - Python 3 with openpyxl installed
#   - CSV files generated by generate_cs_import.py
#
# Usage:
#   cd /Users/clementboschet/Documents/repos/pixid-salesforce
#   bash data/import_cs_2026/import.sh
# =============================================================================

set -e

ORG_ALIAS="PixidProd"
DIR="data/import_cs_2026"

echo "=========================================="
echo "C&S 2026 Import - Step 1: Opportunities"
echo "=========================================="
echo ""
echo "Importing ${DIR}/opportunities.csv..."
sf data import bulk \
  --sobject Opportunity \
  --file "${DIR}/opportunities.csv" \
  --target-org "$ORG_ALIAS" \
  --wait 10

echo ""
echo "Waiting 10 seconds for Opportunity records to be committed..."
sleep 10

echo ""
echo "=========================================="
echo "Step 1b: Query Opportunity IDs and update Charge Maps CSV"
echo "=========================================="

# Query the newly created Opportunities and build a mapping
python3 -c "
import subprocess, json, csv

# Query all Renewal Opportunities for C&S 2026
result = subprocess.run([
    'sf', 'data', 'query',
    '--query', \"SELECT Id, AccountId FROM Opportunity WHERE Name LIKE '% - C&S - 2026' AND RecordType.DeveloperName = 'Renewal'\",
    '--target-org', '${ORG_ALIAS}',
    '--json'
], capture_output=True, text=True)

data = json.loads(result.stdout)
records = data.get('result', {}).get('records', [])

# Build AccountId -> OpportunityId mapping
opp_map = {}
for rec in records:
    opp_map[rec['AccountId']] = rec['Id']

print(f'Found {len(opp_map)} Opportunity records')

# Update charge_maps.csv with SourceOpportunity__c
rows = []
with open('${DIR}/charge_maps.csv', 'r', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    fieldnames = reader.fieldnames
    for row in reader:
        account_id = row['Account__c']
        opp_id = opp_map.get(account_id, '')
        if not opp_id:
            print(f'WARNING: No Opportunity found for Account {account_id}')
        row['SourceOpportunity__c'] = opp_id
        rows.append(row)

with open('${DIR}/charge_maps.csv', 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)

print(f'Updated {len(rows)} Charge Map rows with Opportunity IDs')
"

echo ""
echo "=========================================="
echo "C&S 2026 Import - Step 2: Charge Maps"
echo "=========================================="
echo ""
echo "Importing ${DIR}/charge_maps.csv..."
sf data import bulk \
  --sobject ChargeMap__c \
  --file "${DIR}/charge_maps.csv" \
  --target-org "$ORG_ALIAS" \
  --wait 10

echo ""
echo "Waiting 10 seconds for ChargeMap records to be committed..."
sleep 10

echo ""
echo "=========================================="
echo "Step 2b: Query Charge Map IDs and update Items CSV"
echo "=========================================="

python3 -c "
import subprocess, json, csv

# Query newly created ChargeMaps (Renewal type, C&S related)
result = subprocess.run([
    'sf', 'data', 'query',
    '--query', \"SELECT Id, Account__c FROM ChargeMap__c WHERE Type__c = 'Renewal' AND SourceOpportunity__r.Name LIKE '% - C&S - 2026'\",
    '--target-org', '${ORG_ALIAS}',
    '--json'
], capture_output=True, text=True)

data = json.loads(result.stdout)
records = data.get('result', {}).get('records', [])

# Build AccountId -> ChargeMapId mapping
cm_map = {}
for rec in records:
    cm_map[rec['Account__c']] = rec['Id']

print(f'Found {len(cm_map)} ChargeMap records')

# Update charge_map_items.csv with ChargeMap__c
rows = []
with open('${DIR}/charge_map_items.csv', 'r', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    fieldnames = reader.fieldnames
    for row in reader:
        account_id = row['AccountId_ref']
        cm_id = cm_map.get(account_id, '')
        if not cm_id:
            print(f'WARNING: No ChargeMap found for Account {account_id}')
        row['ChargeMap__c'] = cm_id
        rows.append(row)

# Write final file without the helper AccountId_ref column
final_fields = [f for f in fieldnames if f != 'AccountId_ref']
with open('${DIR}/charge_map_items_final.csv', 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=final_fields, extrasaction='ignore')
    writer.writeheader()
    writer.writerows(rows)

print(f'Written {len(rows)} Charge Map Items to ${DIR}/charge_map_items_final.csv')
"

echo ""
echo "=========================================="
echo "C&S 2026 Import - Step 3: Charge Map Items"
echo "=========================================="
echo ""
echo "Importing ${DIR}/charge_map_items_final.csv..."
sf data import bulk \
  --sobject ChargeMapItem__c \
  --file "${DIR}/charge_map_items_final.csv" \
  --target-org "$ORG_ALIAS" \
  --wait 10

echo ""
echo "=========================================="
echo "IMPORT COMPLETE"
echo "=========================================="
echo ""
echo "Summary:"
echo "  - Opportunities created: 311 (Renewal, Closed - Won)"
echo "  - Charge Maps created: 311 (Renewal, Backlog)"
echo "  - Charge Map Items created: 343"
